services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinema
    ports:
      - "5432:5432/tcp"
  administration-api:
    build:
      context: ./administration
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  administration-frontend:
    build:
      context: ./cinema-admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
