services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinema
    ports:
      - "5432:5432/tcp"
  
  fanside-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: fanside
      MYSQL_ROOT_PASSWORD: Danuraha@1999
    ports:
      - "3306:3306/tcp"

  administration-api:
    build:
      context: ./administration
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  administration-frontend:
    build:
      context: ./cinema-admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  cinema-admin:
    build:
      context: ./cinema-admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
